version: '3.7'
services:
  blagajna:
    container_name: blagajna
    build: .
    image: blagajna:latest
    ports:
      - 80:8080
    networks:
      - blagajna-network
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:latest
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    networks:
      - blagajna-network
    environment:
      - MYSQL_ROOT_PASSWORD=lozinka
      - MYSQL_DATABASE=database
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
volumes:
  mysql-data:
networks:
  blagajna-network:
    driver: bridge
